version: "3"

vars:
  GO_TIMEOUT: 60s
  BIN_DIR: bin
  BINARY: "{{.BIN_DIR}}/codebrev"
  RELEASE_TOOL_BINARY: "{{.BIN_DIR}}/release-tool"
  DIR: "."

tasks:
  default:
    desc: Show all available tasks
    cmds:
      - task --list

  fmt:
    desc: Format Go source files
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet across the module
    cmds:
      - go vet ./...

  modernize:
    desc: uses gopls/modernize on the repo
    cmds:
      - go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...

  lint:
    desc: Run golangci-lint against the module
    deps:
      - fmt
      - vet
      - modernize
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run Go tests with a timeout
    cmds:
      - go test ./... -timeout {{.GO_TIMEOUT}}

  build:
    desc: Build local binary (bin/codebrev)
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BINARY}} .

  build-prod:
    desc: Build optimized binary (bin/codebrev)
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags="-s -w" -o {{.BINARY}} .

  gen:
    desc: Generate codebrev.md for DIR (set DIR=/path/to/project)
    cmds:
      - go run main.go {{.DIR}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  build-release-tool:
    desc: Build the release tool binary
    sources:
      - tools/release-tool/**/*.go
      - tools/release-tool/go.mod
    generates:
      - "{{.RELEASE_TOOL_BINARY}}"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -C tools/release-tool -o ../../{{.RELEASE_TOOL_BINARY}} .

  get-version:
    desc: Print latest version from changelog.md
    deps:
      - build-release-tool
    cmds:
      - ./{{.RELEASE_TOOL_BINARY}} version

  release:
    desc: Commit, tag, and push using the latest changelog entry
    deps:
      - build-release-tool
    cmds:
      - ./{{.RELEASE_TOOL_BINARY}} release
